name: flutter_instagram_stories
homepage: https://github.com/awaik/flutter_instagram_stories
description: Display stories just like Whatsapp & Instagram. Built-in groups (multiple stories with one icon), cache, video, gifs. For now works with Firestore database only.
version: 0.1.3+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.2.1
  rxdart: ^0.23.1
  video_player: ^0.10.8+1
  cached_network_image: ^2.1.0+1
  json_annotation: ^3.0.1
  skeleton_text: ^1.0.0
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.4+2
  dotted_border: ^1.0.5

dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  test: ^1.14.2
